// Autogenerated from json from setup of key in Selvbetjening, using paste special as C#

namespace Fhi.HelseId.Worker;

#nullable disable
public partial class HelseIdClientCredentialsConfiguration
{
    public string clientName { get; set; }
    public string authority { get; set; }
    public string clientId { get; set; }
    public string[] grantTypes { get; set; }
    public string[] scopes { get; set; }
    public string secretType { get; set; }
    public string rsaPrivateKey { get; set; }
    public int rsaKeySizeBits { get; set; }
    public string privateJwk { get; set; }
}