name: Fhi.HelseId.Github-Packages
on:
   pull_request:
    branches:
    - master
   push:
    branches:
    - '*'
    - '!master'
    
jobs:
  build:

    runs-on: windows-latest
    env:
      NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
      VERSION_SHA: ${GITHUB_SHA::8}

    steps:
    - uses: actions/checkout@v1
    - name: Setup Dotnet Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        source-url: https://nuget.pkg.github.com/folkehelseinstituttet/index.json

    - name: Prepare GitHub Packages nuget source
      run: dotnet nuget add source https://nuget.pkg.github.com/folkehelseinstituttet/index.json -n "GitHubPackages" -u folkehelseinstituttet -p $NUGET_AUTH_TOKEN

    - name: Set Nuget Package Version
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        version: 2.0.0-pr-test-${{env.VERSION_SHA}}

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack
      run: dotnet pack --configuration Release Fhi.HelseId

    - name: Publish Package
      run: dotnet nuget push **/*.nupkg --source 'GitHubPackages'