name: Fhi.HelseId.Github-Packages
on:
   pull_request:
    branches:
    - master
   push:
    branches:
    - '*'
    - '!master'
    
jobs:
  build:

    runs-on: windows-latest
    env:
      VERSION_SHA: ${GITHUB_SHA::8}
    steps:
    - uses: actions/checkout@v1
    - name: Setup Dotnet Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        source-url: https://nuget.pkg.github.com/folkehelseinstituttet/index.json

    - name: Set Nuget Package Version
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        version: 2.0.0-pr-test-${{env.VERSION_SHA}}

    - name: Build
      run: dotnet build --configuration Release

    - name: Pack
      run: dotnet pack --configuration Release Fhi.HelseId

    - name: Publish Package
      run: dotnet nuget push *.nupkg --no-symbols --skip-duplicate
      env:
        NUGET_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_PUSH_API_KEY_HELSEID }}