name: Fhi.HelseId.Nuget

on:
  push:
    branches:
      - master

defaults:
  run:
    shell: pwsh

jobs:
  publish:
    name: Build, pack & publish
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: |
            8.0.x
            9.0.x

      - name: Pack
        run: dotnet pack

      - name: Publish nupkg and snupkg to NuGet.org
        run: |
          $packageOutputPath = "artifacts/package/release"
          foreach ($file in (Get-ChildItem $packageOutputPath -Recurse -Include *.nupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_ORG_PUSH_API_KEY_HELSEID }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }
          foreach ($file in (Get-ChildItem $packageOutputPath -Recurse -Include *.snupkg)) {
              dotnet nuget push $file --api-key "${{ secrets.NUGET_ORG_PUSH_API_KEY_HELSEID }}" --source https://api.nuget.org/v3/index.json --skip-duplicate
          }