name: Fhi.HelseId.Github-Packages
on:
   pull_request:
    branches:
    - master
   push:
    branches:
    - '*'
    - '!master'
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup Dotnet Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        source-url: https://nuget.pkg.github.com/folkehelseinstituttet/index.json

    - name: Build
      run: dotnet build --configuration Release

    - name: Prep Version String
      run: echo ::set-env name=VERSION_NUMBER::$(echo 2.0.0-pr-${{GITHUB_SHA::8}})

    - name: Define Package Name
      run: echo ::set-env name=PACKAGE_NAME::$"Fhi.HelseId/bin/Release/Fhi.HelseId.${{ env.VERSION_NUMBER }}.nupkg"

    - name: Set Nuget Package Version
      uses: roryprimrose/set-vs-sdk-project-version@v1
      with:
        version: ${{ env.VERSION_NUMBER }}

    - name: Pack
      run: dotnet pack --configuration Release Fhi.HelseId

    - name: Publish Package
      run: dotnet nuget push Fhi.HelseId/bin/Release/*.nupkg --source https://nuget.pkg.github.com/folkehelseinstituttet/index.json  -ApiKey ${{secrets.GITHUB_TOKEN}}